import type { Metadata } from "next";
import { Provider } from "@/app/provider"; // Asegúrate que la ruta sea correcta
import "./globals.css";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="es" suppressHydrationWarning>
      <body className="bg-bg-light dark:bg-bg-dark text-text-light dark:text-text-dark transition-colors duration-300 font-poppins">
        <Provider>{children}</Provider>
      </body>
    </html>
  );
}
